# Online Python compiler (interpreter) to run Python online.
# Write Python 3 code in this online editor and run it.

def samestring(a,b):
    h=''
    print('samestringgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg')
    print('rrr', len(a))
    print('jjj', len(b))
    #a = list(a)
    #b = list(b)
    #a='ZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZY'
    #b='ZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZY'
    #a='BABAABABBBAA'
    #b='BABAABABBBAA'   
    #a='ZZYZYYZZYYZYZZY'
    #b='ZZYZYYZZYYZYZZY'
    #a = 'BBABAABBA'
    #b = 'BBABAABBA'
    print('rrr', len(a))
    print('jjj', len(b))
    while a or b:
        #print('huuhuhuhu', h)
        ff = 'ZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZYZZYYZZYZYYZZYYZYZZYYZZYZYYZYZZYZYYZZYYZYZZYZYYZZYYZYZZYZZY'

##        q = len(h)
##        ttr = ff[:q]
##        if ttr == h:
            #print('tttr', ttr)
            #print('hhhrrrrrrrrrrrh', h)            
            #print('eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee')
##            pass
##        else:
##            #print('ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd')
##            break
        if not a:
            #print('awwweeeew')
            #print('bwwww', ''.join(b))
            f =''.join(b)
            h=h+f
            break
        
        elif not b:
            #print('awwww')
            #print('aqqqq', ''.join(a))
            #print('bqqq', ''.join(b))
            f = ''.join(a)
            h=h+f
            break
        
        if a==b:
            print('equal')
            h=h+a[0]
            a=a[1:]
        
##        elif a==b and len(a)>len(b):
##            h=h+a[0]
##            a=a[1:]
##
##        elif a==b and len(b)>len(a):
##            h=h+b[0]
##            b=b[1:] 
##        

#         elif a[0]==b[0] and len(a)==1 and len(b)>1:
#             print('huhh')
#             h=h+b[0]
#             b=b[1:]

#         elif a[0]==b[0] and len(b)==1 and len(a)>1:
#             h=h+a[0]
#             a=a[1:]

#         elif a[0]==b[0] and len(b)==1 and len(a)==1:
#             h=h+a[0]
#             a=a[1:]
        
        elif a>b:
            #print('aaaaaaaaaa')
            if len(b)>len(a):
                bb = b[0:len(a)]
                if bb==a:
                    h=h+b[0]
                    b=b[1:]
                else:
                    h=h+b[0]
                    b=b[1:]
            elif len(a)>len(b):
                aa = a[0:len(b)]
                if aa==b:
                    h=h+a[0]
                    a=a[1:]
                    
                else:  
                    h=h+b[0]
                    b=b[1:]
            #print('count_b', count_b)
            #print('a', a)
            #print('b', b)
            
        elif b>a:
            #print('bbbbbbbbbbbbb')
            if len(b)>len(a):
   
                bb = b[0:len(a)]
                if bb==a:
                    #print('equalbbbb')
                    h=h+b[0]
                    b=b[1:]
                else:
                    h=h+a[0]
                    a=a[1:]

            elif len(a)>len(b):
                aa = a[0:len(b)]
                if aa==b:
                    #print('equalbbbb')
                    h=h+a[0]
                    a=a[1:]
                
                else:
                    h=h+a[0]
                    a=a[1:]
            #print('coa', count_a)
            #print('a', a)
            #print('b', b)
        
    #h=h+b
    #u.append(h)
    if ff == h:
        print('rrrrrrrrrrrerggggggggggggggggggggggggggggggggggggggggggggggg')
    print('rqwqw', h)
    #print('a', a)
    #print('b', b)
    #return h

samestring('ZZYZYYZZYYZYZZY', 'ZZYZYYZZYYZYZZY')
